= Delete Entities

include::../../includes/attributes.adoc[]

Existing entity objects can be deleted from the database either explicitly by invoking the remove method or implicitly as a result of a cascade operation.

== Explicit Remove

In order to delete an object from the database it has to first be retrieved (no matter which way) and then in an active transaction, it can be deleted using the remove method:

[source,java]
----
  Employee employee = em.find(Employee.class, 1);

  em.getTransaction().begin();
  em.remove(employee);
  em.getTransaction().commit();
----

The entity object is physically deleted from the database when the transaction is committed.
Embedded objects that are contained in the entity object are also deleted.
If the transaction is rolled back and not committed the object is not deleted.

An `IllegalArgumentException` is thrown by remove if the argument is not an instance of an entity class or if it is a detached entity.
A `TransactionRequiredException` is thrown if there is no active transaction when remove is called because operations that modify the database require an active transaction.

== Cascading Remove

Marking a reference field with `CascadeType.REMOVE` (or `CascadeType.ALL`, which includes `REMOVE`) indicates that remove operations should be cascaded automatically to entity objects that are referenced by that field (multiple entity objects can be referenced by a collection field):

[source,java]
----
@Entity class Employee {
    //...
    @OneToOne(cascade=CascadeType.REMOVE)
    private Address address;
    //...
}
----

In the example above, the Employee entity class contains an address field that references an instance of Address, which is another entity class.
Due to the `CascadeType.REMOVE` setting, when an Employee instance is removed the operation is automatically cascaded to the referenced Address instance, which is then automatically removed as well.
Cascading may continue recursively when applicable (e.g. to entity objects that the Address object references, if any).

== DELETE Queries

DELETE queries provide an alternative way for removing entity objects from the database.
Deleting objects using a DELETE query may be useful especially when many entity objects have to be deleted in one operation.
See DELETE Queries in #JPQL Queries# section explains how to use JPA DELETE queries.
